title: Siddharth Saxena
logo: /assets/img/IMG-20231024-WA0092.jpg
description: Avid tech and video game enthusiast with further interests in nature, badminton, cycling and photography
show_downloads: true
theme: jekyll-theme-minimal
